kind: pipeline
name: test

steps:
  - name: test
    image: python
    commands:
      - pip install python-dotenv
      - python test.py

trigger:
  branch:
  - master
  event:
  - push
  - pull_request
---
kind: pipeline
name: build

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: jeremyaherzog/drone-text-replacement
      username:
        from_secret: docker_user
      password:
        from_secret: docker_pass
      tags:
        - latest
        - "0.1.0" # NOTE: update this semver tag when making changes!
        - ${DRONE_COMMIT_SHA}

trigger:
  branch:
  - master
  event:
  - push

depends_on:
  - test